### ISSUE TITLE
boxee-server-light gives 404 error

### ISSUE THREAD

**Issue by jcompiet** [nicholasserra/boxee-server-light#2]
I'm trying to bring my Boxee Box back to life, but I am having a bit of trouble with it. I have created a container on my proxmox server for this docker image and I am able to run it. I also have edited the DNS entries in my PiHole as described. When I browse to the IP address of the boxee-server-light I get a 404 message. The same happens when I turn on my Boxee Box.

Here is the logging from the docker container of the boxee-server-light:
`root@BoxeeServerLight:/home/boxee-server-light# docker-compose --verbose up
compose.config.config.find: Using configuration files: ./docker-compose.yml
docker.utils.config.find_config_file: Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
docker.utils.config.find_config_file: No config file found
docker.utils.config.find_config_file: Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
docker.utils.config.find_config_file: No config file found
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/version HTTP/1.1" 200 819
compose.cli.command.get_client: docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
compose.cli.command.get_client: Docker base_url: http+docker://localhost
compose.cli.command.get_client: Docker version: Platform={'Name': 'Docker Engine - Community'}, Components=[{'Name': 'Engine', 'Version': '20.10.16', 'Details': {'ApiVersion': '1.41', 'Arch': 'amd64', 'BuildTime': '2022-05-12T09:15:33.000000000+00:00', 'Experimental': 'false', 'GitCommit': 'f756502', 'GoVersion': 'go1.17.10', 'KernelVersion': '5.11.22-3-pve', 'MinAPIVersion': '1.12', 'Os': 'linux'}}, {'Name': 'containerd', 'Version': '1.6.4', 'Details': {'GitCommit': '212e8b6fa2f44b9c21b2798135fc6fb7c53efc16'}}, {'Name': 'runc', 'Version': '1.1.1', 'Details': {'GitCommit': 'v1.1.1-0-g52de29d'}}, {'Name': 'docker-init', 'Version': '0.19.0', 'Details': {'GitCommit': 'de40ad0'}}], Version=20.10.16, ApiVersion=1.41, MinAPIVersion=1.12, GitCommit=f756502, GoVersion=go1.17.10, Os=linux, Arch=amd64, KernelVersion=5.11.22-3-pve, BuildTime=2022-05-12T09:15:33.000000000+00:00
compose.cli.verbose_proxy.proxy_callable: docker inspect_network <- ('boxeeserverlight_default')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/networks/boxeeserverlight_default HTTP/1.1" 404 57
compose.cli.verbose_proxy.proxy_callable: docker info <- ()
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/info HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker info -> {'Architecture': 'x86_64',
 'BridgeNfIp6tables': True,
 'BridgeNfIptables': True,
 'CPUSet': True,
 'CPUShares': True,
 'CgroupDriver': 'systemd',
 'CgroupVersion': '2',
 'ContainerdCommit': {'Expected': '212e8b6fa2f44b9c21b2798135fc6fb7c53efc16',
                      'ID': '212e8b6fa2f44b9c21b2798135fc6fb7c53efc16'},
 'Containers': 3,
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_network <- ('boxee-server-light_default')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/networks/boxee-server-light_default HTTP/1.1" 200 575
compose.cli.verbose_proxy.proxy_callable: docker inspect_network -> {'Attachable': True,
 'ConfigFrom': {'Network': ''},
 'ConfigOnly': False,
 'Containers': {},
 'Created': '2022-05-18T10:13:21.580840921Z',
 'Driver': 'bridge',
 'EnableIPv6': False,
 'IPAM': {'Config': [{'Gateway': '172.18.0.1', 'Subnet': '172.18.0.0/16'}],
          'Driver': 'default',
          'Options': None},
...
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=False, filters={'label': ['com.docker.compose.project=boxee-server-light', 'com.docker.compose.oneoff=False']})
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/containers/json?limit=-1&all=0&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dboxee-server-light%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 3
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=False, filters={'label': ['com.docker.compose.project=boxeeserverlight', 'com.docker.compose.oneoff=False']})
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/containers/json?limit=-1&all=0&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dboxeeserverlight%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 3
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={'label': ['com.docker.compose.project=boxee-server-light', 'com.docker.compose.service=web', 'com.docker.compose.oneoff=False']})
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/containers/json?limit=-1&all=1&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dboxee-server-light%22%2C+%22com.docker.compose.service%3Dweb%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 1306
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 1 items)
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- ('758e6f031690a31a7ad021dc82d8a5d6619dc3e3b342bec32d1210b58fffaedb')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/containers/758e6f031690a31a7ad021dc82d8a5d6619dc3e3b342bec32d1210b58fffaedb/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {'AppArmorProfile': 'docker-default',
 'Args': [],
 'Config': {'AttachStderr': False,
            'AttachStdin': False,
            'AttachStdout': False,
            'Cmd': None,
            'Domainname': '',
            'Entrypoint': ['./docker-entrypoint.sh'],
            'Env': ['DATABASE_URL=postgres://postgres:password@db:5432/boxee',
                    'ENVIRONMENT=local',
...
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={'label': ['com.docker.compose.project=boxee-server-light', 'com.docker.compose.service=db', 'com.docker.compose.oneoff=False']})
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/containers/json?limit=-1&all=1&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dboxee-server-light%22%2C+%22com.docker.compose.service%3Ddb%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 1374
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 1 items)
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- ('41bc843df918bc482ae4fce8568e64041c6572ad7cc81c36bc351ae1daa3b803')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/containers/41bc843df918bc482ae4fce8568e64041c6572ad7cc81c36bc351ae1daa3b803/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {'AppArmorProfile': 'docker-default',
 'Args': ['postgres'],
 'Config': {'AttachStderr': False,
            'AttachStdin': False,
            'AttachStdout': False,
            'Cmd': ['postgres'],
            'Domainname': '',
            'Entrypoint': ['docker-entrypoint.sh'],
            'Env': ['POSTGRES_DB=boxee',
                    'POSTGRES_PASSWORD=password',
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_image <- ('boxee-server-light_web')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/images/boxee-server-light_web/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker inspect_image -> {'Architecture': 'amd64',
 'Author': '',
 'Comment': '',
 'Config': {'AttachStderr': False,
            'AttachStdin': False,
            'AttachStdout': False,
            'Cmd': None,
            'Domainname': '',
            'Entrypoint': ['./docker-entrypoint.sh'],
            'Env': ['PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_image <- ('postgres')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/images/postgres/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker inspect_image -> {'Architecture': 'amd64',
 'Author': '',
 'Comment': '',
 'Config': {'AttachStderr': False,
            'AttachStdin': False,
            'AttachStdout': False,
            'Cmd': ['postgres'],
            'Domainname': '',
            'Entrypoint': ['docker-entrypoint.sh'],
            'Env': ['PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/14/bin',
...
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={'label': ['com.docker.compose.project=boxee-server-light', 'com.docker.compose.service=web', 'com.docker.compose.oneoff=False']})
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/containers/json?limit=-1&all=1&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dboxee-server-light%22%2C+%22com.docker.compose.service%3Dweb%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 1306
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 1 items)
compose.cli.verbose_proxy.proxy_callable: docker inspect_image <- ('boxee-server-light_web')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/images/boxee-server-light_web/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker inspect_image -> {'Architecture': 'amd64',
 'Author': '',
 'Comment': '',
 'Config': {'AttachStderr': False,
            'AttachStdin': False,
            'AttachStdout': False,
            'Cmd': None,
            'Domainname': '',
            'Entrypoint': ['./docker-entrypoint.sh'],
            'Env': ['PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- ('758e6f031690a31a7ad021dc82d8a5d6619dc3e3b342bec32d1210b58fffaedb')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/containers/758e6f031690a31a7ad021dc82d8a5d6619dc3e3b342bec32d1210b58fffaedb/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {'AppArmorProfile': 'docker-default',
 'Args': [],
 'Config': {'AttachStderr': False,
            'AttachStdin': False,
            'AttachStdout': False,
            'Cmd': None,
            'Domainname': '',
            'Entrypoint': ['./docker-entrypoint.sh'],
            'Env': ['DATABASE_URL=postgres://postgres:password@db:5432/boxee',
                    'ENVIRONMENT=local',
...
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={'label': ['com.docker.compose.project=boxee-server-light', 'com.docker.compose.service=db', 'com.docker.compose.oneoff=False']})
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/containers/json?limit=-1&all=1&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dboxee-server-light%22%2C+%22com.docker.compose.service%3Ddb%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 1374
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 1 items)
compose.cli.verbose_proxy.proxy_callable: docker inspect_image <- ('postgres')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/images/postgres/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker inspect_image -> {'Architecture': 'amd64',
 'Author': '',
 'Comment': '',
 'Config': {'AttachStderr': False,
            'AttachStdin': False,
            'AttachStdout': False,
            'Cmd': ['postgres'],
            'Domainname': '',
            'Entrypoint': ['docker-entrypoint.sh'],
            'Env': ['PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/14/bin',
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- ('41bc843df918bc482ae4fce8568e64041c6572ad7cc81c36bc351ae1daa3b803')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/containers/41bc843df918bc482ae4fce8568e64041c6572ad7cc81c36bc351ae1daa3b803/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {'AppArmorProfile': 'docker-default',
 'Args': ['postgres'],
 'Config': {'AttachStderr': False,
            'AttachStdin': False,
            'AttachStdout': False,
            'Cmd': ['postgres'],
            'Domainname': '',
            'Entrypoint': ['docker-entrypoint.sh'],
            'Env': ['POSTGRES_DB=boxee',
                    'POSTGRES_PASSWORD=password',
...
compose.parallel.feed_queue: Pending: {<Service: db>, <Service: web>}
compose.parallel.feed_queue: Starting producer thread for <Service: db>
Starting boxee-server-light_db_1_2e9be23c74a2 ... 
compose.parallel.feed_queue: Starting producer thread for <Service: web>
compose.parallel.feed_queue: Pending: {<Container: boxee-server-light_db_1_2e9be23c74a2 (41bc84)>}
compose.parallel.feed_queue: Starting producer thread for <Container: boxee-server-light_db_1_2e9be23c74a2 (41bc84)>
Starting boxee-server-light_web_1_cba655016758 ... 
compose.parallel.feed_queue: Pending: {<Container: boxee-server-light_web_1_cba655016758 (758e6f)>}
compose.parallel.feed_queue: Starting producer thread for <Container: boxee-server-light_web_1_cba655016758 (758e6f)>
compose.cli.verbose_proxy.proxy_callable: docker attach <- ('41bc843df918bc482ae4fce8568e64041c6572ad7cc81c36bc351ae1daa3b803', stdout=True, stderr=True, stream=True)
urllib3.connectionpool._make_request: http://localhost:None "POST /v1.25/containers/41bc843df918bc482ae4fce8568e64041c6572ad7cc81c36bc351ae1daa3b803/attach?logs=0&stdout=1&stderr=1&stream=1 HTTP/1.1" 101 0
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/containers/41bc843df918bc482ae4fce8568e64041c6572ad7cc81c36bc351ae1daa3b803/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker attach -> <docker.types.daemon.CancellableStream object at 0x7fbeb37f55c0>
compose.cli.verbose_proxy.proxy_callable: docker start <- ('41bc843df918bc482ae4fce8568e64041c6572ad7cc81c36bc351ae1daa3b803')
compose.cli.verbose_proxy.proxy_callable: docker attach <- ('758e6f031690a31a7ad021dc82d8a5d6619dc3e3b342bec32d1210b58fffaedb', stdout=True, stderr=True, stream=True)
urllib3.connectionpool._make_request: http://localhost:None "POST /v1.25/containers/758e6f031690a31a7ad021dc82d8a5d6619dc3e3b342bec32d1210b58fffaedb/attach?logs=0&stdout=1&stderr=1&stream=1 HTTP/1.1" 101 0
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/containers/758e6f031690a31a7ad021dc82d8a5d6619dc3e3b342bec32d1210b58fffaedb/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker attach -> <docker.types.daemon.CancellableStream object at 0x7fbeb37f8668>
compose.cli.verbose_proxy.proxy_callable: docker start <- ('758e6f031690a31a7ad021dc82d8a5d6619dc3e3b342bec32d1210b58fffaedb')
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
urllib3.connectionpool._make_request: http://localhost:None "POST /v1.25/containers/41bc843df918bc482ae4fce8568e64041c6572ad7cc81c36bc351ae1daa3b803/start HTTP/1.1" 204 0
compose.cli.verbose_proxy.proxy_callable: docker start -> None
Starting boxee-server-light_db_1_2e9be23c74a2  ... done-light_db_1_2e9be23c74a2 (41bc84)>
compose.parallel.feed_queue: Pending: set()
compose.parallel.parallel_execute_iter: Finished processing: <Service: db>
compose.parallel.feed_queue: Pending: set()
urllib3.connectionpool._make_request: http://localhost:None "POST /v1.25/containers/758e6f031690a31a7ad021dc82d8a5d6619dc3e3b342bec32d1210b58fffaedb/start HTTP/1.1" 204 0
compose.cli.verbose_proxy.proxy_callable: docker start -> None
compose.parallel.parallel_execute_iter: Finished processing: <Container: boxee-serverStarting boxee-server-light_web_1_cba655016758 ... done
compose.parallel.feed_queue: Pending: set()
compose.parallel.parallel_execute_iter: Finished processing: <Service: web>
compose.parallel.feed_queue: Pending: set()
Attaching to boxee-server-light_db_1_2e9be23c74a2, boxee-server-light_web_1_cba655016758
compose.cli.verbose_proxy.proxy_callable: docker events <- (filters={'label': ['com.docker.compose.project=boxee-server-light', 'com.docker.compose.oneoff=False']}, decode=True)
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/events?filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dboxee-server-light%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker events -> <docker.types.daemon.CancellableStream object at 0x7fbeb37f5da0>
web_1_cba655016758 | Starting development server
db_1_2e9be23c74a2 | 
db_1_2e9be23c74a2 | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1_2e9be23c74a2 | 
db_1_2e9be23c74a2 | 2022-05-19 05:47:51.995 UTC [1] LOG:  starting PostgreSQL 14.3 (Debian 14.3-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
db_1_2e9be23c74a2 | 2022-05-19 05:47:51.995 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1_2e9be23c74a2 | 2022-05-19 05:47:51.995 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1_2e9be23c74a2 | 2022-05-19 05:47:51.999 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1_2e9be23c74a2 | 2022-05-19 05:47:52.005 UTC [25] LOG:  database system was shut down at 2022-05-19 05:47:42 UTC
db_1_2e9be23c74a2 | 2022-05-19 05:47:52.016 UTC [1] LOG:  database system is ready to accept connections
web_1_cba655016758 |  * Environment: development
web_1_cba655016758 |  * Debug mode: on
web_1_cba655016758 |  * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
web_1_cba655016758 |  * Restarting with stat
web_1_cba655016758 |  * Debugger is active!
web_1_cba655016758 |  * Debugger PIN: 954-399-571
web_1_cba655016758 |  * Debugger is active!
web_1_cba655016758 |  * Debugger PIN: 341-752-597
web_1_cba655016758 | 192.168.1.213 - - [19/May/2022 05:47:58] "GET / HTTP/1.1" 404 -
web_1_cba655016758 | INFO:werkzeug:192.168.1.213 - - [19/May/2022 05:47:58] "GET / HTTP/1.1" 404 -
web_1_cba655016758 | /usr/local/lib/python2.7/site-packages/flask/app.py:2174: UserWarning: Current server name '192.168.1.141' doesn't match configured server name 'boxee.test'
web_1_cba655016758 |   subdomain=subdomain,
web_1_cba655016758 | 192.168.1.213 - - [19/May/2022 05:58:19] "GET / HTTP/1.1" 404 -
web_1_cba655016758 | INFO:werkzeug:192.168.1.213 - - [19/May/2022 05:58:19] "GET / HTTP/1.1" 404 -
`

**Comment by nicholasserra** [comment]
This looks to be an issue with your container orchestration and not with this package. These logs aren't from the container, but are instead from whatever you're using to run it. Hence the docker-compose warnings. I'd try running this straight up via docker command and see what you get. Also try running ENVIRONMENT as anything but "local" to see if that triggers the right url.
